const params=new URLSearchParams(location.search),type=params.get('type')||'interview';
const common=[{name:'destination',label:'Наименование организации / ведомства',required:true},{name:'manager',label:'Должность руководителя',required:true}];
const passport=[{name:'passport_series',label:'Серия паспорта',required:true},{name:'passport_number',label:'Номер паспорта',required:true},{name:'passport_issuer',label:'Кем выдан',required:true},{name:'passport_issue_date',label:'Дата выдачи',type:'date',required:true}];
const defs={
interview:{title:'Заявление на собеседование',description:'Официальный запрос на рассмотрение кандидатуры для трудоустройства',sections:[['Кому',common],['Кандидатура',[{name:'desired_position',label:'Желаемая должность',required:true},{name:'current_position',label:'Текущая должность'}]],['Паспорт',passport]]},
promotion:{title:'Заявление на повышение в должности',description:'Официальное обращение к руководству с просьбой о рассмотрении кандидатуры для продвижения по службе',sections:[['Кому',common],['Работа',[{name:'current_position',label:'Текущая должность',required:true},{name:'desired_position',label:'Желаемая должность',required:true},{name:'start_work_day',label:'Дата начала работы',placeholder:'Например: 15 день',required:true},{name:'initial_position',label:'Начальная должность',required:true}]]]},
dismissal:{title:'Заявление на увольнение',description:'Официальное уведомление работодателя о расторжении трудового договора',sections:[['Кому',common],['Работа',[{name:'position',label:'Должность',required:true},{name:'reason',label:'Причина увольнения',required:true},{name:'dismissal_day',label:'Дата увольнения',placeholder:'Например: 25 день',required:true}]],['Паспорт',passport]]},
vacation:{title:'Заявление на отпуск',description:'Официальный запрос на предоставление ежегодного оплачиваемого отпуска',sections:[['Кому',common],['Отпуск',[{name:'position',label:'Должность',required:true},{name:'start_day',label:'Дата начала',placeholder:'Например: 15 день',required:true},{name:'end_day',label:'Дата окончания',placeholder:'Например: 25 день',required:true},{name:'days_count',label:'Количество календарных дней',required:true}]]]},
citizenship:{title:'Заявление о приёме в гражданство',description:'Официальное обращение о приёме в гражданство',sections:[['Кому',[{name:'migration_service',label:'Наименование миграционной службы',required:true}]],['Сведения',[{name:'citizenship',label:'Гражданство',required:true},{name:'birth_place',label:'Место рождения',required:true},{name:'nationality',label:'Национальность',required:true},{name:'residence_start_day',label:'Дата начала проживания',required:true},{name:'document_type',label:'Вид документа',required:true},{name:'document_number',label:'Номер документа',required:true},{name:'document_issue_day',label:'Дата выдачи',required:true}]]]},
mortgage:{title:'Заявление на ипотечный кредит',description:'Запрос на предоставление ипотечного кредита для приобретения недвижимости',sections:[['Кому',[{name:'bank',label:'Наименование банка',required:true}]],['Недвижимость',[{name:'property_type',label:'Вид недвижимости',required:true},{name:'property_address',label:'Адрес недвижимости',full:true,required:true},{name:'property_price',label:'Стоимость',type:'number',required:true},{name:'currency',label:'Валюта',required:true},{name:'down_payment',label:'Первоначальный взнос',type:'number',required:true},{name:'term',label:'Срок',type:'number',required:true},{name:'term_unit',label:'Единица срока',required:true}]]]},
credit:{title:'Заявление на кредит',description:'Официальный запрос на предоставление кредита',sections:[['Кому',[{name:'credit_org',label:'Наименование банка или кредитной организации',required:true}]],['Кредит',[{name:'credit_type',label:'Вид кредита',required:true},{name:'amount',label:'Сумма цифрами',type:'number',required:true},{name:'currency',label:'Валюта',required:true},{name:'term',label:'Срок',type:'number',required:true},{name:'term_unit',label:'Единица срока',required:true}]],['Паспорт',passport]]},
report:{title:'Докладная записка',description:'Сообщение руководству о нарушении или событии',sections:[['Кому',common],['Событие',[{name:'event_day',label:'Дата',required:true},{name:'event_time',label:'Время',required:true},{name:'worker_name',label:'ФИО работника',required:true},{name:'worker_position',label:'Должность работника',required:true},{name:'violation',label:'Описание нарушения',full:true,required:true},{name:'location',label:'Место нарушения',required:true},{name:'details',label:'Подробное описание',full:true,required:true},{name:'recorded_by',label:'Кем или чем зафиксировано',required:true},{name:'violation_character',label:'Характер нарушения',required:true},{name:'impact',label:'Вид воздействия / мера',required:true}]]]},
explanatory:{title:'Объяснительная записка',description:'Письменное объяснение обстоятельств события',sections:[['Кому',common],['Объяснение',[{name:'event_day',label:'Дата',required:true},{name:'event_time',label:'Время',required:true},{name:'violation',label:'Описание нарушения',full:true,required:true},{name:'reason',label:'Подробное описание причины',full:true,required:true}]]]},
lawsuit:{title:'Исковое заявление',description:'Официальное обращение в суд',sections:[['Суд',[{name:'court',label:'Наименование суда',required:true},{name:'plaintiff_address',label:'Адрес истца',required:true},{name:'defendant',label:'ФИО или наименование ответчика',required:true},{name:'defendant_address',label:'Адрес ответчика',required:true}]],['Иск',[{name:'claim_subject',label:'Предмет иска',required:true},{name:'period_start',label:'Дата начала',required:true},{name:'period_end',label:'Дата окончания',required:true},{name:'relationship',label:'Описание взаимоотношений',full:true,required:true},{name:'violation',label:'Описание нарушения',full:true,required:true},{name:'consequences',label:'Последствия',full:true,required:true},{name:'legal_basis',label:'Нормативные акты',full:true,required:true},{name:'claim_1',label:'Требование 1',full:true,required:true},{name:'claim_2',label:'Требование 2',full:true},{name:'attachments',label:'Приложения',full:true}]]]},
border:{title:'Заявление на выезд за границу',description:'Официальный запрос на разрешение выезда за границу',sections:[['Кому',[{name:'border_service',label:'Наименование пограничной службы или учреждения',required:true}]],['Поездка',[{name:'citizenship',label:'Гражданство',required:true},{name:'passport_series',label:'Серия паспорта',required:true},{name:'passport_number',label:'Номер паспорта',required:true},{name:'passport_issuer',label:'Кем и когда выдан',full:true,required:true},{name:'destination_country',label:'Страна назначения',required:true},{name:'start_day',label:'Дата начала',required:true},{name:'end_day',label:'Дата окончания',required:true},{name:'purpose',label:'Цель поездки',full:true,required:true}]]]},
bankruptcy:{title:'Заявление о банкротстве',description:'Официальное обращение о финансовой несостоятельности',sections:[['Кому',[{name:'bank',label:'Наименование банка или финансового учреждения',required:true}]],['Задолженность',[{name:'citizenship',label:'Гражданство',required:true},{name:'debt_type',label:'Вид задолженности',required:true},{name:'amount',label:'Сумма цифрами',type:'number',required:true},{name:'currency',label:'Валюта',required:true},{name:'reason',label:'Причина невозможности погашения',full:true,required:true}]],['Паспорт',passport]]}};
const def=defs[type]||defs.interview;document.getElementById('title').textContent=def.title;document.getElementById('description').textContent=def.description;
const fields=document.getElementById('fields');def.sections.forEach(([title,list])=>{const s=document.createElement('section');s.className='field-section';s.innerHTML='<h2>'+title+'</h2><div class="fields"></div>';const g=s.querySelector('.fields');list.forEach(f=>{const w=document.createElement('div');w.className='field'+(f.full?' full':'');w.innerHTML='<label>'+f.label+(f.required?' <em>обязательно</em>':'')+'</label><input name="'+f.name+'" type="'+(f.type||'text')+'" placeholder="'+(f.placeholder||'')+'" '+(f.required?'required':'')+'>';g.appendChild(w)});fields.appendChild(s)});
const storageKey='draft_'+type;try{const saved=JSON.parse(localStorage.getItem(storageKey)||'{}');Object.entries(saved).forEach(([k,v])=>{const el=document.querySelector('[name="'+k+'"]');if(el)el.value=v})}catch{}
const realDate=new Date().toLocaleDateString('ru-RU');document.getElementById('realDate').innerHTML=realDate+' <b>(реальная дата)</b>';
async function fillProfile(){try{const p=await ZB.currentProfile();if(!p)return;const map={passport_series:p.passport_series,passport_number:p.passport_number,passport_issuer:p.passport_issuer,passport_issue_date:p.passport_issue_date,citizenship:p.citizenship,birth_place:p.birth_place,nationality:p.nationality,residence_address:p.residence_address,registration_address:p.registration_address};Object.entries(map).forEach(([k,v])=>{const el=document.querySelector('[name="'+k+'"]');if(el&&v){el.value=v;el.readOnly=true;el.title='Данные взяты из профиля гражданина'}})}catch(e){console.warn('Не удалось загрузить профиль',e)}}fillProfile();
const form=document.getElementById('applicationForm');form.addEventListener('input',()=>{const o={};new FormData(form).forEach((v,k)=>o[k]=v);localStorage.setItem(storageKey,JSON.stringify(o))});form.addEventListener('submit',e=>{e.preventDefault();const data={};new FormData(form).forEach((v,k)=>data[k]=v);if(!/^\d+$/.test(data.game_day)){alert('Введите корректный игровой день.');return}sessionStorage.setItem('preview_data',JSON.stringify({type,data,gameDay:Number(data.game_day)}));location.href='preview.html'});