const params=new URLSearchParams(location.search),type=params.get('type')||'interview';
const profileKeys=['full_name','birth_date','passport_series','passport_number','passport_issuer','passport_issue_date','citizenship','birth_place','nationality','residence_address','registration_address'];
const common=[{name:'destination',label:'Куда подаётся заявление',placeholder:'Например: Единая служба спасения',required:true},{name:'manager',label:'Должность руководителя',placeholder:'Например: Начальнику департамента',required:true}];
const passport=['passport_series','passport_number','passport_issuer','passport_issue_date'];
const defs={
interview:{title:'Заявление на собеседование',description:'Официальный запрос на рассмотрение кандидатуры для трудоустройства',sections:[['Кому',common],['Кандидатура',[{name:'desired_position',label:'Желаемая должность',placeholder:'На какую должность хотите устроиться?',required:true}]]],profile:passport},
promotion:{title:'Заявление на повышение в должности',description:'Просьба рассмотреть кандидатуру для продвижения по службе',sections:[['Кому',common],['Работа',[{name:'current_position',label:'Текущая должность',placeholder:'Ваша должность сейчас',required:true},{name:'desired_position',label:'Желаемая должность',placeholder:'На какую должность хотите перейти?',required:true},{name:'start_work_day',label:'Дата начала работы',type:'date',required:true},{name:'initial_position',label:'Начальная должность',placeholder:'С какой должности начали работать?',required:true}]]]},
dismissal:{title:'Заявление на увольнение',description:'Официальное уведомление работодателя о расторжении трудового договора',sections:[['Кому',common],['Работа',[{name:'position',label:'Должность',placeholder:'С какой должности увольняетесь?',required:true},{name:'reason',label:'Причина увольнения',placeholder:'Например: по собственному желанию',full:true,required:true},{name:'dismissal_day',label:'Дата увольнения',type:'date',required:true}]],['Паспорт',[]]],profile:passport},
vacation:{title:'Заявление на отпуск',description:'Официальный запрос на предоставление ежегодного оплачиваемого отпуска',sections:[['Кому',common],['Отпуск',[{name:'position',label:'Должность',placeholder:'Ваша текущая должность',required:true},{name:'start_day',label:'Дата начала',type:'date',required:true},{name:'end_day',label:'Дата окончания',type:'date',required:true},{name:'days_count',label:'Количество календарных дней',type:'number',placeholder:'Например: 14',required:true}]]]},
citizenship:{title:'Заявление о приёме в гражданство',description:'Официальное обращение о приёме в гражданство',sections:[['Кому',[{name:'migration_service',label:'Наименование миграционной службы',placeholder:'Полное название службы',required:true}]],['Сведения',[{name:'residence_start_day',label:'Дата начала проживания',type:'date',required:true},{name:'document_type',label:'Вид документа',placeholder:'Например: ВНЖ',required:true},{name:'document_number',label:'Номер документа',placeholder:'Номер документа',required:true},{name:'document_issue_day',label:'Дата выдачи документа',type:'date',required:true}]]],profile:['full_name','birth_date','citizenship','birth_place','nationality']},
mortgage:{title:'Заявление на ипотечный кредит',description:'Запрос на предоставление ипотечного кредита для приобретения недвижимости',sections:[['Кому',[{name:'bank',label:'Наименование банка',placeholder:'Полное название банка',required:true}]],['Недвижимость',[{name:'property_type',label:'Вид недвижимости',placeholder:'Квартира, дом и т.д.',required:true},{name:'property_address',label:'Адрес недвижимости',placeholder:'Полный адрес',full:true,required:true},{name:'property_price',label:'Стоимость цифрами',type:'number',required:true},{name:'property_price_words',label:'Стоимость прописью',placeholder:'Например: пять миллионов рублей',full:true,required:true},{name:'currency',label:'Валюта',placeholder:'Например: ₽',required:true},{name:'down_payment',label:'Первоначальный взнос цифрами',type:'number',required:true},{name:'down_payment_words',label:'Первоначальный взнос прописью',placeholder:'Сумма словами',full:true,required:true},{name:'term',label:'Срок',type:'number',required:true},{name:'term_unit',label:'Единица срока',placeholder:'Лет или месяцев',required:true}]]],profile:['full_name']},
credit:{title:'Заявление на кредит',description:'Официальный запрос на предоставление кредита',sections:[['Кому',[{name:'credit_org',label:'Наименование банка или кредитной организации',placeholder:'Полное название',required:true}]],['Кредит',[{name:'credit_type',label:'Вид кредита',placeholder:'Какой кредит нужен?',required:true},{name:'amount',label:'Сумма цифрами',type:'number',required:true},{name:'amount_words',label:'Сумма прописью',placeholder:'Например: пятьсот тысяч рублей',full:true,required:true},{name:'currency',label:'Валюта',placeholder:'Например: ₽',required:true},{name:'term',label:'Срок',type:'number',required:true},{name:'term_unit',label:'Единица срока',placeholder:'Лет или месяцев',required:true}]]],profile:['full_name','passport_series','passport_number','passport_issuer']},
report:{title:'Докладная записка',description:'Сообщение руководству о нарушении или событии',sections:[['Кому',common],['Событие',[{name:'event_day',label:'Дата события',type:'date',required:true},{name:'event_time',label:'Время события',type:'time',required:true},{name:'worker_name',label:'ФИО работника',placeholder:'Фамилия Имя Отчество',required:true},{name:'worker_position',label:'Должность работника',placeholder:'Должность',required:true},{name:'violation',label:'Описание нарушения',placeholder:'Кратко опишите нарушение',full:true,required:true},{name:'location',label:'Место нарушения',placeholder:'Где произошло событие?',required:true},{name:'details',label:'Подробное описание',placeholder:'Что именно произошло?',full:true,required:true},{name:'recorded_by',label:'Кем или чем зафиксировано',placeholder:'Свидетель, камера, документ и т.д.',required:true},{name:'violation_character',label:'Характер нарушения',placeholder:'В чём состоит нарушение?',full:true,required:true},{name:'impact',label:'Вид воздействия / мера',placeholder:'Какую меру предлагаете?',full:true,required:true}]]]},
explanatory:{title:'Объяснительная записка',description:'Письменное объяснение обстоятельств события',sections:[['Кому',common],['Объяснение',[{name:'event_day',label:'Дата события',type:'date',required:true},{name:'event_time',label:'Время события',type:'time',required:true},{name:'violation',label:'Что произошло',placeholder:'Опишите ситуацию',full:true,required:true},{name:'reason',label:'Подробное описание причины',placeholder:'Почему это произошло?',full:true,required:true}]]]},
lawsuit:{title:'Исковое заявление',description:'Официальное обращение в суд',sections:[['Суд',[{name:'court',label:'Наименование суда',placeholder:'Полное название суда',required:true},{name:'plaintiff_address',label:'Адрес истца',placeholder:'По умолчанию адрес проживания',required:true},{name:'defendant',label:'ФИО или наименование ответчика',required:true},{name:'defendant_address',label:'Адрес ответчика',required:true}]],['Иск',[{name:'claim_subject',label:'Предмет иска',required:true},{name:'period_start',label:'Дата начала',type:'date',required:true},{name:'period_end',label:'Дата окончания',type:'date',required:true},{name:'relationship',label:'Описание взаимоотношений',full:true,required:true},{name:'violation',label:'Описание нарушения',full:true,required:true},{name:'consequences',label:'Последствия',full:true,required:true},{name:'legal_basis',label:'Нормативные акты',placeholder:'Статьи/нормы',full:true,required:true},{name:'claim_1',label:'Требование 1',full:true,required:true},{name:'claim_2',label:'Требование 2',full:true},{name:'attachments',label:'Приложения',placeholder:'Перечислите документы',full:true}]]],profile:['full_name','residence_address']},
border:{title:'Заявление на выезд за границу',description:'Официальный запрос на разрешение выезда за границу',sections:[['Кому',[{name:'border_service',label:'Наименование пограничной службы или учреждения',required:true}]],['Поездка',[{name:'destination_country',label:'Страна назначения',required:true},{name:'start_day',label:'Дата начала',type:'date',required:true},{name:'end_day',label:'Дата окончания',type:'date',required:true},{name:'purpose',label:'Цель поездки',placeholder:'Туризм, работа, посещение родственников',full:true,required:true}]]],profile:['citizenship','full_name','passport_series','passport_number','passport_issuer']},
bankruptcy:{title:'Заявление о банкротстве',description:'Официальное обращение о финансовой несостоятельности',sections:[['Кому',[{name:'bank',label:'Наименование банка или финансового учреждения',required:true}]],['Задолженность',[{name:'debt_type',label:'Вид задолженности',required:true},{name:'amount',label:'Сумма цифрами',type:'number',required:true},{name:'amount_words',label:'Сумма прописью',placeholder:'Сумма словами',full:true,required:true},{name:'currency',label:'Валюта',required:true},{name:'reason',label:'Причина невозможности погашения',full:true,required:true}]]],profile:['citizenship','full_name','passport_series','passport_number','passport_issuer']}
};
const def=defs[type]||defs.interview;document.getElementById('title').textContent=def.title;document.getElementById('description').textContent=def.description;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let profile={};
function formatDate(v){if(!v)return '';const [y,m,d]=String(v).split('-');return d&&m&&y?`${d}.${m}.${y}`:v}
function renderProfileNotice(){const required=[...(def.profile||[])];const missing=required.filter(k=>!profile[k]);const box=document.createElement('section');box.className='field-section profile-source';box.innerHTML=`<h2>Данные из профиля</h2><p class="profile-note">ФИО, паспортные и личные сведения подставляются автоматически. Их не нужно переписывать вручную.</p><div class="profile-chips">${required.map(k=>`<span class="profile-chip ${profile[k]?'ok':'missing'}">${esc({full_name:'ФИО',birth_date:'Дата рождения',passport_series:'Серия паспорта',passport_number:'Номер паспорта',passport_issuer:'Кем выдан',passport_issue_date:'Дата выдачи',citizenship:'Гражданство',birth_place:'Место рождения',nationality:'Национальность',residence_address:'Адрес проживания',registration_address:'Адрес регистрации'}[k]||k)} ${profile[k]?'✓':'!'}</span>`).join('')}</div>${missing.length?`<div class="profile-warning">Не хватает данных: <b>${missing.map(k=>({full_name:'ФИО',birth_date:'дата рождения',passport_series:'серия паспорта',passport_number:'номер паспорта',passport_issuer:'кем выдан',passport_issue_date:'дата выдачи',citizenship:'гражданство',birth_place:'место рождения',nationality:'национальность',residence_address:'адрес проживания'}[k]||k)).join(', ')}</b>. <a href="profile.html">Заполнить профиль →</a></div>`:''}</section>`;return box}
async function boot(){const p=await ZB.requireCitizen();if(!p)return;profile=p;const container=document.getElementById('fields');container.before(renderProfileNotice());
for(const [sectionTitle,list] of def.sections){if(!list.length)continue;const s=document.createElement('section');s.className='field-section';s.innerHTML='<h2>'+esc(sectionTitle)+'</h2><div class="fields"></div>';const grid=s.querySelector('.fields');list.forEach(f=>{const w=document.createElement('div');w.className='field'+(f.full?' full':'');w.innerHTML=`<label>${esc(f.label)}${f.required?' <em>обязательно</em>':''}</label><input name="${esc(f.name)}" type="${f.type||'text'}" placeholder="${esc(f.placeholder||'')}" ${f.required?'required':''}><small class="field-help">${esc(f.placeholder||'Введите значение, которое должно попасть в документ.')}</small>`;grid.appendChild(w)});container.appendChild(s)}
const saved=JSON.parse(localStorage.getItem('draft_'+type)||'{}');Object.entries(saved).forEach(([k,v])=>{const el=document.querySelector(`[name="${k}"]`);if(el)el.value=v});document.getElementById('realDate').innerHTML=`${new Date().toLocaleDateString('ru-RU')} <b>(реальная дата)</b>`;
const game=document.getElementById('gameDay');if(saved.game_day!=null)game.value=saved.game_day;document.getElementById('applicationForm').addEventListener('input',()=>{const data={};new FormData(document.getElementById('applicationForm')).forEach((v,k)=>data[k]=v);localStorage.setItem('draft_'+type,JSON.stringify(data))});document.getElementById('applicationForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.target),data={...profile};fd.forEach((v,k)=>data[k]=v);data.birth_date=formatDate(data.birth_date);data.passport_issue_date=formatDate(data.passport_issue_date);['start_work_day','dismissal_day','start_day','end_day','residence_start_day','document_issue_day','event_day','period_start','period_end'].forEach(k=>{if(data[k])data[k]=formatDate(data[k])});data.game_day=String(game.value);const missing=(def.profile||[]).filter(k=>!profile[k]);if(missing.length){alert('Сначала заполните профиль: '+missing.join(', '));return}sessionStorage.setItem('preview_data',JSON.stringify({type,data}));location.href='preview.html'});}
boot().catch(e=>{console.error(e);alert('Не удалось открыть форму: '+e.message)});